// ================= MEDIA DATABASE =================
// All movies, TV series, K-Dramas, and Turkish Series with real download links

export const MEDIA_DB = {
  movies: [
    // ===== CLASSICS =====
    { title: "The Shawshank Redemption", year: "1994", genre: "Drama", rating: "9.3", download: "https://yts.si/movies/the-shawshank-redemption-1994" },
    { title: "The Godfather", year: "1972", genre: "Crime", rating: "9.2", download: "https://yts.si/movies/the-godfather-1972" },
    { title: "The Godfather Part II", year: "1974", genre: "Crime", rating: "9.0", download: "https://yts.si/movies/the-godfather-part-ii-1974" },
    { title: "The Dark Knight", year: "2008", genre: "Action", rating: "9.0", download: "https://yts.si/movies/the-dark-knight-2008" },
    { title: "12 Angry Men", year: "1957", genre: "Drama", rating: "9.0", download: "https://yts.si/movies/12-angry-men-1957" },
    { title: "Schindler's List", year: "1993", genre: "Drama", rating: "8.9", download: "https://yts.si/movies/schindlers-list-1993" },
    { title: "Pulp Fiction", year: "1994", genre: "Crime", rating: "8.9", download: "https://yts.si/movies/pulp-fiction-1994" },
    { title: "The Lord of the Rings: Return of the King", year: "2003", genre: "Fantasy", rating: "8.9", download: "https://yts.si/movies/the-lord-of-the-rings-the-return-of-the-king-2003" },
    { title: "The Good, the Bad and the Ugly", year: "1966", genre: "Western", rating: "8.8", download: "https://yts.si/movies/the-good-the-bad-and-the-ugly-1966" },
    { title: "Fight Club", year: "1999", genre: "Drama", rating: "8.8", download: "https://yts.si/movies/fight-club-1999" },
    { title: "Forrest Gump", year: "1994", genre: "Romance", rating: "8.8", download: "https://yts.si/movies/forrest-gump-1994" },
    { title: "Inception", year: "2010", genre: "Sci-Fi", rating: "8.8", download: "https://yts.si/movies/inception-2010" },
    { title: "The Matrix", year: "1999", genre: "Sci-Fi", rating: "8.7", download: "https://yts.si/movies/the-matrix-1999" },
    { title: "Goodfellas", year: "1990", genre: "Crime", rating: "8.7", download: "https://yts.si/movies/goodfellas-1990" },
    { title: "Interstellar", year: "2014", genre: "Sci-Fi", rating: "8.6", download: "https://yts.si/movies/interstellar-2014" },
    { title: "The Lord of the Rings: Fellowship of the Ring", year: "2001", genre: "Fantasy", rating: "8.8", download: "https://yts.si/movies/the-lord-of-the-rings-the-fellowship-of-the-ring-2001" },
    { title: "The Lord of the Rings: Two Towers", year: "2002", genre: "Fantasy", rating: "8.7", download: "https://yts.si/movies/the-lord-of-the-rings-the-two-towers-2002" },
    { title: "Star Wars: Empire Strikes Back", year: "1980", genre: "Sci-Fi", rating: "8.7", download: "https://yts.si/movies/star-wars-episode-v-the-empire-strikes-back-1980" },
    { title: "Star Wars: A New Hope", year: "1977", genre: "Sci-Fi", rating: "8.6", download: "https://yts.si/movies/star-wars-episode-iv-a-new-hope-1977" },
    { title: "The Silence of the Lambs", year: "1991", genre: "Thriller", rating: "8.6", download: "https://yts.si/movies/the-silence-of-the-lambs-1991" },
    
    // ===== ACTION & ADVENTURE =====
    { title: "Avengers Endgame", year: "2019", genre: "Action", rating: "8.4", download: "https://yts.si/movies/avengers-endgame-2019" },
    { title: "Avengers Infinity War", year: "2018", genre: "Action", rating: "8.4", download: "https://yts.si/movies/avengers-infinity-war-2018" },
    { title: "Gladiator", year: "2000", genre: "Action", rating: "8.5", download: "https://yts.si/movies/gladiator-2000" },
    { title: "Braveheart", year: "1995", genre: "Action", rating: "8.3", download: "https://yts.si/movies/braveheart-1995" },
    { title: "The Avengers", year: "2012", genre: "Action", rating: "8.0", download: "https://yts.si/movies/the-avengers-2012" },
    { title: "Mad Max Fury Road", year: "2015", genre: "Action", rating: "8.1", download: "https://yts.si/movies/mad-max-fury-road-2015" },
    { title: "John Wick", year: "2014", genre: "Action", rating: "7.4", download: "https://yts.si/movies/john-wick-2014" },
    { title: "John Wick Chapter 2", year: "2017", genre: "Action", rating: "7.5", download: "https://yts.si/movies/john-wick-chapter-2-2017" },
    { title: "John Wick Chapter 3", year: "2019", genre: "Action", rating: "7.4", download: "https://yts.si/movies/john-wick-chapter-3-parabellum-2019" },
    { title: "The Raid", year: "2011", genre: "Action", rating: "7.6", download: "https://yts.si/movies/the-raid-2011" },
    
    // ===== SCI-FI =====
    { title: "Joker", year: "2019", genre: "Thriller", rating: "8.4", download: "https://yts.si/movies/joker-2019" },
    { title: "Blade Runner 2049", year: "2017", genre: "Sci-Fi", rating: "8.0", download: "https://yts.si/movies/blade-runner-2049-2017" },
    { title: "The Martian", year: "2015", genre: "Sci-Fi", rating: "8.0", download: "https://yts.si/movies/the-martian-2015" },
    { title: "Gravity", year: "2013", genre: "Sci-Fi", rating: "7.7", download: "https://yts.si/movies/gravity-2013" },
    { title: "Ex Machina", year: "2014", genre: "Sci-Fi", rating: "7.7", download: "https://yts.si/movies/ex-machina-2014" },
    { title: "Arrival", year: "2016", genre: "Sci-Fi", rating: "7.9", download: "https://yts.si/movies/arrival-2016" },
    
    // ===== ANIMATION =====
    { title: "The Lion King", year: "1994", genre: "Animation", rating: "8.5", download: "https://yts.si/movies/the-lion-king-1994" },
    { title: "Toy Story", year: "1995", genre: "Animation", rating: "8.3", download: "https://yts.si/movies/toy-story-1995" },
    { title: "Toy Story 3", year: "2010", genre: "Animation", rating: "8.3", download: "https://yts.si/movies/toy-story-3-2010" },
    { title: "Spirited Away", year: "2001", genre: "Animation", rating: "8.6", download: "https://yts.si/movies/spirited-away-2001" },
    { title: "Howl's Moving Castle", year: "2004", genre: "Animation", rating: "8.2", download: "https://yts.si/movies/howls-moving-castle-2004" },
    { title: "Finding Nemo", year: "2003", genre: "Animation", rating: "8.2", download: "https://yts.si/movies/finding-nemo-2003" },
    { title: "Wall-E", year: "2008", genre: "Animation", rating: "8.4", download: "https://yts.si/movies/walle-2008" },
    { title: "Up", year: "2009", genre: "Animation", rating: "8.3", download: "https://yts.si/movies/up-2009" },
    
    // ===== ROMANCE =====
    { title: "Titanic", year: "1997", genre: "Romance", rating: "7.9", download: "https://yts.si/movies/titanic-1997" },
    { title: "The Notebook", year: "2004", genre: "Romance", rating: "7.8", download: "https://yts.si/movies/the-notebook-2004" },
    { title: "Crazy Rich Asians", year: "2018", genre: "Romance", rating: "6.9", download: "https://yts.si/movies/crazy-rich-asians-2018" },
    { title: "A Star is Born", year: "2018", genre: "Romance", rating: "7.6", download: "https://yts.si/movies/a-star-is-born-2018" },
    { title: "La La Land", year: "2016", genre: "Romance", rating: "8.0", download: "https://yts.si/movies/la-la-land-2016" },
    
    // ===== COMEDY =====
    { title: "The Hangover", year: "2009", genre: "Comedy", rating: "7.7", download: "https://yts.si/movies/the-hangover-2009" },
    { title: "Superbad", year: "2007", genre: "Comedy", rating: "7.6", download: "https://yts.si/movies/superbad-2007" },
    { title: "The 40 Year Old Virgin", year: "2005", genre: "Comedy", rating: "7.1", download: "https://yts.si/movies/the-40-year-old-virgin-2005" },
    { title: "Bridesmaids", year: "2011", genre: "Comedy", rating: "6.8", download: "https://yts.si/movies/bridesmaids-2011" },
    { title: "The Grand Budapest Hotel", year: "2014", genre: "Comedy", rating: "8.1", download: "https://yts.si/movies/the-grand-budapest-hotel-2014" },
    
    // ===== HORROR =====
    { title: "The Shining", year: "1980", genre: "Horror", rating: "8.4", download: "https://yts.si/movies/the-shining-1980" },
    { title: "Get Out", year: "2017", genre: "Horror", rating: "7.8", download: "https://yts.si/movies/get-out-2017" },
    { title: "A Quiet Place", year: "2018", genre: "Horror", rating: "7.5", download: "https://yts.si/movies/a-quiet-place-2018" },
    { title: "The Conjuring", year: "2013", genre: "Horror", rating: "7.5", download: "https://yts.si/movies/the-conjuring-2013" },
    { title: "It", year: "2017", genre: "Horror", rating: "7.3", download: "https://yts.si/movies/it-2017" },
    
    // ===== THRILLER =====
    { title: "The Departed", year: "2006", genre: "Thriller", rating: "8.5", download: "https://yts.si/movies/the-departed-2006" },
    { title: "Se7en", year: "1995", genre: "Thriller", rating: "8.6", download: "https://yts.si/movies/se7en-1995" },
    { title: "The Usual Suspects", year: "1995", genre: "Thriller", rating: "8.5", download: "https://yts.si/movies/the-usual-suspects-1995" },
    { title: "Memento", year: "2000", genre: "Thriller", rating: "8.4", download: "https://yts.si/movies/memento-2000" },
    { title: "Prisoners", year: "2013", genre: "Thriller", rating: "8.1", download: "https://yts.si/movies/prisoners-2013" },
  ],
  
  tvSeries: [
    // ===== INTERNATIONAL TV SERIES =====
    { title: "Game of Thrones", year: "2011", seasons: "8", rating: "9.2", download: "https://o2tvseries.com/game-of-thrones/" },
    { title: "Breaking Bad", year: "2008", seasons: "5", rating: "9.5", download: "https://o2tvseries.com/breaking-bad/" },
    { title: "The Office", year: "2005", seasons: "9", rating: "8.9", download: "https://o2tvseries.com/the-office-us/" },
    { title: "Stranger Things", year: "2016", seasons: "4", rating: "8.7", download: "https://o2tvseries.com/stranger-things/" },
    { title: "The Witcher", year: "2019", seasons: "3", rating: "8.2", download: "https://o2tvseries.com/the-witcher/" },
    { title: "Money Heist", year: "2017", seasons: "5", rating: "8.2", download: "https://o2tvseries.com/money-heist/" },
    { title: "Better Call Saul", year: "2015", seasons: "6", rating: "8.9", download: "https://o2tvseries.com/better-call-saul/" },
    { title: "The Walking Dead", year: "2010", seasons: "11", rating: "8.1", download: "https://o2tvseries.com/the-walking-dead/" },
    { title: "The Crown", year: "2016", seasons: "6", rating: "8.6", download: "https://o2tvseries.com/the-crown/" },
    { title: "The Mandalorian", year: "2019", seasons: "3", rating: "8.7", download: "https://o2tvseries.com/the-mandalorian/" },
    { title: "House of the Dragon", year: "2022", seasons: "2", rating: "8.5", download: "https://o2tvseries.com/house-of-the-dragon/" },
    { title: "The Last of Us", year: "2023", seasons: "1", rating: "8.8", download: "https://o2tvseries.com/the-last-of-us/" },
    { title: "Wednesday", year: "2022", seasons: "1", rating: "8.1", download: "https://o2tvseries.com/wednesday/" },
    { title: "The Boys", year: "2019", seasons: "4", rating: "8.7", download: "https://o2tvseries.com/the-boys/" },
    { title: "Succession", year: "2018", seasons: "4", rating: "8.8", download: "https://o2tvseries.com/succession/" },
    { title: "Yellowstone", year: "2018", seasons: "5", rating: "8.7", download: "https://o2tvseries.com/yellowstone/" },
    { title: "Peaky Blinders", year: "2013", seasons: "6", rating: "8.8", download: "https://o2tvseries.com/peaky-blinders/" },
    { title: "The Handmaid's Tale", year: "2017", seasons: "5", rating: "8.4", download: "https://o2tvseries.com/the-handmaids-tale/" },
    { title: "This Is Us", year: "2016", seasons: "6", rating: "8.7", download: "https://o2tvseries.com/this-is-us/" },
    { title: "Black Mirror", year: "2011", seasons: "6", rating: "8.7", download: "https://o2tvseries.com/black-mirror/" },
    
    // ===== TURKISH SERIES =====
    { title: "Diriliş: Ertuğrul", year: "2014", seasons: "5", rating: "8.9", download: "https://turkish123.com/drama/dirilis-ertugrul" },
    { title: "Kuruluş: Osman", year: "2019", seasons: "5", rating: "8.7", download: "https://turkish123.com/drama/kurulus-osman" },
    { title: "Muhteşem Yüzyıl", year: "2011", seasons: "4", rating: "8.8", download: "https://turkish123.com/drama/muhtesem-yuzyil" },
    { title: "Muhteşem Yüzyıl: Kösem", year: "2015", seasons: "2", rating: "8.0", download: "https://turkish123.com/drama/muhtesem-yuzyil-kosem" },
    { title: "Kara Sevda", year: "2015", seasons: "2", rating: "8.5", download: "https://turkish123.com/drama/kara-sevda" },
    { title: "Aşk-ı Memnu", year: "2008", seasons: "2", rating: "8.4", download: "https://turkish123.com/drama/ask-i-memnu" },
    { title: "Fatmagül'ün Suçu Ne?", year: "2010", seasons: "2", rating: "8.6", download: "https://turkish123.com/drama/fatmagulun-sucu-ne" },
    { title: "Kuzey Güney", year: "2011", seasons: "2", rating: "8.3", download: "https://turkish123.com/drama/kuzey-guney" },
    { title: "Ezel", year: "2009", seasons: "2", rating: "8.7", download: "https://turkish123.com/drama/ezel" },
    { title: "Kınalı Kar", year: "2002", seasons: "1", rating: "7.5", download: "https://turkish123.com/drama/kinali-kar" },
    { title: "Yaprak Dökümü", year: "2006", seasons: "5", rating: "8.1", download: "https://turkish123.com/drama/yaprak-dokumu" },
    { title: "Aşk ve Ceza", year: "2010", seasons: "2", rating: "7.8", download: "https://turkish123.com/drama/ask-ve-ceza" },
    { title: "Paramparça", year: "2014", seasons: "3", rating: "8.0", download: "https://turkish123.com/drama/paramparca" },
    { title: "Kara Para Aşk", year: "2014", seasons: "2", rating: "8.2", download: "https://turkish123.com/drama/kara-para-ask" },
    { title: "Medcezir", year: "2013", seasons: "2", rating: "8.1", download: "https://turkish123.com/drama/medcezir" },
    { title: "Cesur ve Güzel", year: "2016", seasons: "1", rating: "7.9", download: "https://turkish123.com/drama/cesur-ve-guzel" },
    { title: "Içerde", year: "2016", seasons: "1", rating: "8.3", download: "https://turkish123.com/drama/icerde" },
    { title: "Savaşçı", year: "2017", seasons: "3", rating: "8.0", download: "https://turkish123.com/drama/savasci" },
    { title: "Kalk Gidelim", year: "2018", seasons: "3", rating: "7.5", download: "https://turkish123.com/drama/kalk-gidelim" },
    { title: "Sen Anlat Karadeniz", year: "2018", seasons: "3", rating: "8.1", download: "https://turkish123.com/drama/sen-anlat-karadeniz" },
    { title: "Hercai", year: "2019", seasons: "3", rating: "8.4", download: "https://turkish123.com/drama/hercai" },
    { title: "Elif", year: "2014", seasons: "6", rating: "7.8", download: "https://turkish123.com/drama/elif" },
    { title: "Yasak Elma", year: "2018", seasons: "7", rating: "7.5", download: "https://turkish123.com/drama/yasak-elma" },
    { title: "Ateşböceği", year: "2017", seasons: "2", rating: "7.2", download: "https://turkish123.com/drama/atesbocegi" },
    { title: "Kara Ekmek", year: "2015", seasons: "1", rating: "6.5", download: "https://turkish123.com/drama/kara-ekmek" },
    { title: "Gülperi", year: "2018", seasons: "2", rating: "7.0", download: "https://turkish123.com/drama/gulperi" },
    { title: "Bir Aile Hikayesi", year: "2019", seasons: "1", rating: "6.8", download: "https://turkish123.com/drama/bir-aile-hikayesi" },
    { title: "Küçük Gelin", year: "2013", seasons: "3", rating: "7.2", download: "https://turkish123.com/drama/kucuk-gelin" },
    { title: "Aşk ve Mavi", year: "2016", seasons: "2", rating: "7.1", download: "https://turkish123.com/drama/ask-ve-mavi" },
    { title: "Kaderimin Yazıldığı Gün", year: "2014", seasons: "2", rating: "7.0", download: "https://turkish123.com/drama/kaderimin-yazildigi-gun" },
    { title: "Kara Gün", year: "2017", seasons: "2", rating: "6.8", download: "https://turkish123.com/drama/kara-gun" },
    { title: "Kiralık Aşk", year: "2015", seasons: "2", rating: "8.2", download: "https://turkish123.com/drama/kiralik-ask" },
    { title: "Aşk Laftan Anlamaz", year: "2016", seasons: "1", rating: "8.0", download: "https://turkish123.com/drama/ask-laflen-anlamaz" },
    { title: "Erkenci Kuş", year: "2018", seasons: "1", rating: "8.3", download: "https://turkish123.com/drama/erkenci-kus" },
    { title: "Bay Yanlış", year: "2020", seasons: "1", rating: "7.8", download: "https://turkish123.com/drama/bay-yanlis" },
    { title: "Sen Çal Kapımı", year: "2020", seasons: "1", rating: "8.1", download: "https://turkish123.com/drama/sen-cal-kapimi" },
    { title: "Aşk 101", year: "2020", seasons: "2", rating: "8.0", download: "https://turkish123.com/drama/ask-101" },
    { title: "Mucize Doktor", year: "2019", seasons: "3", rating: "8.0", download: "https://turkish123.com/drama/mucize-doktor" },
    { title: "Kefaret", year: "2020", seasons: "1", rating: "7.0", download: "https://turkish123.com/drama/kefaret" },
    { title: "Zümrüdüanka", year: "2019", seasons: "2", rating: "6.5", download: "https://turkish123.com/drama/zumruduanka" },
    { title: "Güzel Günler", year: "2020", seasons: "1", rating: "6.5", download: "https://turkish123.com/drama/guzel-gunler" },
    { title: "Sefirin Kızı", year: "2019", seasons: "2", rating: "7.5", download: "https://turkish123.com/drama/sefirin-kizi" },
    { title: "Sol Yanim", year: "2020", seasons: "1", rating: "6.0", download: "https://turkish123.com/drama/sol-yanim" },
    { title: "Yeni Hayat", year: "2020", seasons: "1", rating: "6.5", download: "https://turkish123.com/drama/yeni-hayat" },
    { title: "Kara Kök", year: "2021", seasons: "1", rating: "7.5", download: "https://turkish123.com/drama/kara-kok" },
    { title: "Ada Masalı", year: "2021", seasons: "1", rating: "7.0", download: "https://turkish123.com/drama/ada-masali" },
    { title: "Sadakatsiz", year: "2020", seasons: "2", rating: "7.8", download: "https://turkish123.com/drama/sadakatsiz" },
    { title: "Kırmızı Oda", year: "2020", seasons: "2", rating: "7.5", download: "https://turkish123.com/drama/kirmizi-oda" },
    { title: "Uzak Şehir", year: "2021", seasons: "1", rating: "6.8", download: "https://turkish123.com/drama/uzak-sehir" },
    { title: "Kara Kuzular", year: "2015", seasons: "1", rating: "7.8", download: "https://turkish123.com/drama/kara-kuzular" },
    { title: "Aşk Kırmızı", year: "2019", seasons: "1", rating: "7.5", download: "https://turkish123.com/drama/ask-kirmizi" },
    { title: "Hayat Bazen Tatlıdır", year: "2016", seasons: "1", rating: "7.0", download: "https://turkish123.com/drama/hayat-bazen-tatlidir" },
    { title: "Ruhsar", year: "2001", seasons: "4", rating: "7.2", download: "https://turkish123.com/drama/ruhsar" },
    { title: "Sıla", year: "2006", seasons: "2", rating: "7.8", download: "https://turkish123.com/drama/sila" },
    { title: "Aşk-ı Kıyamet", year: "2016", seasons: "1", rating: "6.5", download: "https://turkish123.com/drama/ask-i-kiyamet" },
    { title: "Kara Yılan", year: "2021", seasons: "1", rating: "6.0", download: "https://turkish123.com/drama/kara-yilan" },
  ],
  
  kdramas: [
    { title: "Crash Landing on You", year: "2019", episodes: "16", rating: "9.0", download: "https://kissasian.li/drama/crash-landing-on-you" },
    { title: "Descendants of the Sun", year: "2016", episodes: "16", rating: "8.8", download: "https://kissasian.li/drama/descendants-of-the-sun" },
    { title: "Goblin", year: "2016", episodes: "16", rating: "8.9", download: "https://kissasian.li/drama/goblin" },
    { title: "Itaewon Class", year: "2020", episodes: "16", rating: "8.6", download: "https://kissasian.li/drama/itaewon-class" },
    { title: "Kingdom", year: "2019", episodes: "12", rating: "8.9", download: "https://kissasian.li/drama/kingdom" },
    { title: "Squid Game", year: "2021", episodes: "9", rating: "8.8", download: "https://kissasian.li/drama/squid-game" },
    { title: "Vincenzo", year: "2021", episodes: "20", rating: "8.7", download: "https://kissasian.li/drama/vincenzo" },
    { title: "Hospital Playlist", year: "2020", episodes: "12", rating: "8.8", download: "https://kissasian.li/drama/hospital-playlist" },
    { title: "Reply 1988", year: "2015", episodes: "20", rating: "9.0", download: "https://kissasian.li/drama/reply-1988" },
    { title: "Mr. Sunshine", year: "2018", episodes: "24", rating: "8.9", download: "https://kissasian.li/drama/mr-sunshine" },
    { title: "What's Wrong with Secretary Kim", year: "2018", episodes: "16", rating: "8.1", download: "https://kissasian.li/drama/whats-wrong-with-secretary-kim" },
    { title: "My Love from the Star", year: "2013", episodes: "21", rating: "8.4", download: "https://kissasian.li/drama/my-love-from-the-star" },
    { title: "Moon Lovers: Scarlet Heart Ryeo", year: "2016", episodes: "20", rating: "8.4", download: "https://kissasian.li/drama/moon-lovers-scarlet-heart-ryeo" },
    { title: "The King: Eternal Monarch", year: "2020", episodes: "16", rating: "8.1", download: "https://kissasian.li/drama/the-king-eternal-monarch" },
    { title: "Start-Up", year: "2020", episodes: "16", rating: "8.0", download: "https://kissasian.li/drama/start-up" },
    { title: "It's Okay to Not Be Okay", year: "2020", episodes: "16", rating: "8.6", download: "https://kissasian.li/drama/its-okay-to-not-be-okay" },
    { title: "Hotel del Luna", year: "2019", episodes: "16", rating: "8.7", download: "https://kissasian.li/drama/hotel-del-luna" },
    { title: "Extraordinary Attorney Woo", year: "2022", episodes: "16", rating: "8.9", download: "https://kissasian.li/drama/extraordinary-attorney-woo" },
    { title: "Alchemy of Souls", year: "2022", episodes: "30", rating: "8.8", download: "https://kissasian.li/drama/alchemy-of-souls" },
    { title: "The Glory", year: "2022", episodes: "16", rating: "8.8", download: "https://kissasian.li/drama/the-glory" },
    { title: "Business Proposal", year: "2022", episodes: "12", rating: "8.2", download: "https://kissasian.li/drama/business-proposal" },
    { title: "Twenty-Five Twenty-One", year: "2022", episodes: "16", rating: "8.5", download: "https://kissasian.li/drama/twenty-five-twenty-one" },
    { title: "Our Blues", year: "2022", episodes: "20", rating: "8.5", download: "https://kissasian.li/drama/our-blues" },
    { title: "My Mister", year: "2018", episodes: "16", rating: "9.0", download: "https://kissasian.li/drama/my-mister" },
    { title: "Signal", year: "2016", episodes: "16", rating: "9.0", download: "https://kissasian.li/drama/signal" },
    { title: "Prison Playbook", year: "2017", episodes: "16", rating: "8.9", download: "https://kissasian.li/drama/prison-playbook" },
    { title: "Strong Woman Do Bong-soon", year: "2017", episodes: "16", rating: "8.1", download: "https://kissasian.li/drama/strong-woman-do-bong-soon" },
    { title: "Weightlifting Fairy Kim Bok-joo", year: "2016", episodes: "16", rating: "8.4", download: "https://kissasian.li/drama/weightlifting-fairy-kim-bok-joo" },
    { title: "While You Were Sleeping", year: "2017", episodes: "32", rating: "8.4", download: "https://kissasian.li/drama/while-you-were-sleeping" },
    { title: "The Legend of the Blue Sea", year: "2016", episodes: "20", rating: "8.1", download: "https://kissasian.li/drama/the-legend-of-the-blue-sea" },
    { title: "W: Two Worlds", year: "2016", episodes: "16", rating: "8.3", download: "https://kissasian.li/drama/w-two-worlds" },
    { title: "Fight for My Way", year: "2017", episodes: "16", rating: "8.0", download: "https://kissasian.li/drama/fight-for-my-way" },
    { title: "She Was Pretty", year: "2015", episodes: "16", rating: "7.9", download: "https://kissasian.li/drama/she-was-pretty" },
    { title: "Kill Me, Heal Me", year: "2015", episodes: "20", rating: "8.5", download: "https://kissasian.li/drama/kill-me-heal-me" },
    { title: "Oh My Venus", year: "2015", episodes: "16", rating: "8.0", download: "https://kissasian.li/drama/oh-my-venus" },
    { title: "Master's Sun", year: "2013", episodes: "17", rating: "8.3", download: "https://kissasian.li/drama/masters-sun" },
    { title: "Coffee Prince", year: "2007", episodes: "17", rating: "8.3", download: "https://kissasian.li/drama/coffee-prince" },
    { title: "Secret Garden", year: "2010", episodes: "20", rating: "8.2", download: "https://kissasian.li/drama/secret-garden" },
    { title: "Boys Over Flowers", year: "2009", episodes: "25", rating: "7.9", download: "https://kissasian.li/drama/boys-over-flowers" },
    { title: "Full House", year: "2004", episodes: "16", rating: "7.8", download: "https://kissasian.li/drama/full-house" },
    { title: "Winter Sonata", year: "2002", episodes: "20", rating: "8.0", download: "https://kissasian.li/drama/winter-sonata" },
    { title: "Stairway to Heaven", year: "2003", episodes: "20", rating: "8.1", download: "https://kissasian.li/drama/stairway-to-heaven" },
    { title: "Autumn in My Heart", year: "2000", episodes: "16", rating: "8.0", download: "https://kissasian.li/drama/autumn-in-my-heart" },
  ],
  
  turkishSeries: [
    // ===== HISTORICAL TURKISH SERIES =====
    { title: "Diriliş: Ertuğrul", year: "2014", episodes: "5 Seasons", rating: "8.9", download: "https://turkish123.com/drama/dirilis-ertugrul" },
    { title: "Kuruluş: Osman", year: "2019", episodes: "5 Seasons", rating: "8.7", download: "https://turkish123.com/drama/kurulus-osman" },
    { title: "Muhteşem Yüzyıl", year: "2011", episodes: "4 Seasons", rating: "8.8", download: "https://turkish123.com/drama/muhtesem-yuzyil" },
    { title: "Muhteşem Yüzyıl: Kösem", year: "2015", episodes: "2 Seasons", rating: "8.0", download: "https://turkish123.com/drama/muhtesem-yuzyil-kosem" },
    { title: "Payitaht Abdülhamid", year: "2017", episodes: "5 Seasons", rating: "8.3", download: "https://turkish123.com/drama/payitaht-abdulhamid" },
    { title: "Mehmed: Fetihler Sultanı", year: "2024", episodes: "1 Season", rating: "8.1", download: "https://turkish123.com/drama/mehmed-fetihler-sultani" },
    
    // ===== ROMANTIC TURKISH SERIES =====
    { title: "Kara Sevda", year: "2015", episodes: "2 Seasons", rating: "8.5", download: "https://turkish123.com/drama/kara-sevda" },
    { title: "Aşk-ı Memnu", year: "2008", episodes: "2 Seasons", rating: "8.4", download: "https://turkish123.com/drama/ask-i-memnu" },
    { title: "Fatmagül'ün Suçu Ne?", year: "2010", episodes: "2 Seasons", rating: "8.6", download: "https://turkish123.com/drama/fatmagulun-sucu-ne" },
    { title: "Kuzey Güney", year: "2011", episodes: "2 Seasons", rating: "8.3", download: "https://turkish123.com/drama/kuzey-guney" },
    { title: "Hercai", year: "2019", episodes: "3 Seasons", rating: "8.4", download: "https://turkish123.com/drama/hercai" },
    { title: "Erkenci Kuş", year: "2018", episodes: "1 Season", rating: "8.3", download: "https://turkish123.com/drama/erkenci-kus" },
    { title: "Sen Çal Kapımı", year: "2020", episodes: "1 Season", rating: "8.1", download: "https://turkish123.com/drama/sen-cal-kapimi" },
    { title: "Kiralık Aşk", year: "2015", episodes: "2 Seasons", rating: "8.2", download: "https://turkish123.com/drama/kiralik-ask" },
    { title: "Aşk Laftan Anlamaz", year: "2016", episodes: "1 Season", rating: "8.0", download: "https://turkish123.com/drama/ask-laflen-anlamaz" },
    { title: "Bay Yanlış", year: "2020", episodes: "1 Season", rating: "7.8", download: "https://turkish123.com/drama/bay-yanlis" },
    { title: "Aşk 101", year: "2020", episodes: "2 Seasons", rating: "8.0", download: "https://turkish123.com/drama/ask-101" },
    
    // ===== DRAMA TURKISH SERIES =====
    { title: "Ezel", year: "2009", episodes: "2 Seasons", rating: "8.7", download: "https://turkish123.com/drama/ezel" },
    { title: "Içerde", year: "2016", episodes: "1 Season", rating: "8.3", download: "https://turkish123.com/drama/icerde" },
    { title: "Savaşçı", year: "2017", episodes: "3 Seasons", rating: "8.0", download: "https://turkish123.com/drama/savasci" },
    { title: "Kara Para Aşk", year: "2014", episodes: "2 Seasons", rating: "8.2", download: "https://turkish123.com/drama/kara-para-ask" },
    { title: "Cesur ve Güzel", year: "2016", episodes: "1 Season", rating: "7.9", download: "https://turkish123.com/drama/cesur-ve-guzel" },
    { title: "Medcezir", year: "2013", episodes: "2 Seasons", rating: "8.1", download: "https://turkish123.com/drama/medcezir" },
    { title: "Paramparça", year: "2014", episodes: "3 Seasons", rating: "8.0", download: "https://turkish123.com/drama/paramparca" },
    { title: "Sadakatsiz", year: "2020", episodes: "2 Seasons", rating: "7.8", download: "https://turkish123.com/drama/sadakatsiz" },
    
    // ===== COMEDY TURKISH SERIES =====
    { title: "Avrupa Yakası", year: "2004", episodes: "10 Seasons", rating: "8.5", download: "https://turkish123.com/drama/avrupa-yakasi" },
    { title: "Kardeş Payı", year: "2014", episodes: "2 Seasons", rating: "8.2", download: "https://turkish123.com/drama/kardes-payi" },
    { title: "Güldür Güldür Show", year: "2013", episodes: "8 Seasons", rating: "8.0", download: "https://turkish123.com/drama/guldur-guldur-show" },
    { title: "Jet Sosyete", year: "2018", episodes: "2 Seasons", rating: "7.8", download: "https://turkish123.com/drama/jet-sosyete" },
    { title: "Aile", year: "2023", episodes: "1 Season", rating: "8.0", download: "https://turkish123.com/drama/aile" },
    
    // ===== FAMILY TURKISH SERIES =====
    { title: "Yaprak Dökümü", year: "2006", episodes: "5 Seasons", rating: "8.1", download: "https://turkish123.com/drama/yaprak-dokumu" },
    { title: "Aşk ve Ceza", year: "2010", episodes: "2 Seasons", rating: "7.8", download: "https://turkish123.com/drama/ask-ve-ceza" },
    { title: "Elif", year: "2014", episodes: "6 Seasons", rating: "7.8", download: "https://turkish123.com/drama/elif" },
    { title: "Yasak Elma", year: "2018", episodes: "7 Seasons", rating: "7.5", download: "https://turkish123.com/drama/yasak-elma" },
    { title: "Sen Anlat Karadeniz", year: "2018", episodes: "3 Seasons", rating: "8.1", download: "https://turkish123.com/drama/sen-anlat-karadeniz" },
    { title: "Mucize Doktor", year: "2019", episodes: "3 Seasons", rating: "8.0", download: "https://turkish123.com/drama/mucize-doktor" },
    { title: "Gülperi", year: "2018", episodes: "2 Seasons", rating: "7.0", download: "https://turkish123.com/drama/gulperi" },
    
    // ===== ACTION TURKISH SERIES =====
    { title: "Kara Ekmek", year: "2015", episodes: "1 Season", rating: "6.5", download: "https://turkish123.com/drama/kara-ekmek" },
    { title: "Kara Gün", year: "2017", episodes: "2 Seasons", rating: "6.8", download: "https://turkish123.com/drama/kara-gun" },
    { title: "Kınalı Kar", year: "2002", episodes: "1 Season", rating: "7.5", download: "https://turkish123.com/drama/kinali-kar" },
    { title: "Ateşböceği", year: "2017", episodes: "2 Seasons", rating: "7.2", download: "https://turkish123.com/drama/atesbocegi" },
  ]
};
