export const americanMovies = [
  // ===== CLASSICS =====
  { title: "The Shawshank Redemption", year: "1994", genre: "Drama", rating: "9.3", download: "https://yts.mx/movies/the-shawshank-redemption-1994" },
  { title: "The Godfather", year: "1972", genre: "Crime", rating: "9.2", download: "https://yts.mx/movies/the-godfather-1972" },
  { title: "The Godfather Part II", year: "1974", genre: "Crime", rating: "9.0", download: "https://yts.mx/movies/the-godfather-part-ii-1974" },
  { title: "12 Angry Men", year: "1957", genre: "Drama", rating: "9.0", download: "https://yts.mx/movies/12-angry-men-1957" },
  { title: "Schindler's List", year: "1993", genre: "Drama", rating: "8.9", download: "https://yts.mx/movies/schindlers-list-1993" },
  { title: "Pulp Fiction", year: "1994", genre: "Crime", rating: "8.9", download: "https://yts.mx/movies/pulp-fiction-1994" },
  { title: "The Dark Knight", year: "2008", genre: "Action", rating: "9.0", download: "https://yts.mx/movies/the-dark-knight-2008" },
  { title: "Forrest Gump", year: "1994", genre: "Romance", rating: "8.8", download: "https://yts.mx/movies/forrest-gump-1994" },
  { title: "Fight Club", year: "1999", genre: "Drama", rating: "8.8", download: "https://yts.mx/movies/fight-club-1999" },
  { title: "Inception", year: "2010", genre: "Sci-Fi", rating: "8.8", download: "https://yts.mx/movies/inception-2010" },
  { title: "The Matrix", year: "1999", genre: "Sci-Fi", rating: "8.7", download: "https://yts.mx/movies/the-matrix-1999" },
  { title: "Goodfellas", year: "1990", genre: "Crime", rating: "8.7", download: "https://yts.mx/movies/goodfellas-1990" },
  { title: "Interstellar", year: "2014", genre: "Sci-Fi", rating: "8.6", download: "https://yts.mx/movies/interstellar-2014" },
  { title: "The Lord of the Rings: Fellowship of the Ring", year: "2001", genre: "Fantasy", rating: "8.8", download: "https://yts.mx/movies/the-lord-of-the-rings-the-fellowship-of-the-ring-2001" },
  { title: "The Lord of the Rings: Two Towers", year: "2002", genre: "Fantasy", rating: "8.7", download: "https://yts.mx/movies/the-lord-of-the-rings-the-two-towers-2002" },
  { title: "The Lord of the Rings: Return of the King", year: "2003", genre: "Fantasy", rating: "8.9", download: "https://yts.mx/movies/the-lord-of-the-rings-the-return-of-the-king-2003" },
  { title: "Star Wars: Empire Strikes Back", year: "1980", genre: "Sci-Fi", rating: "8.7", download: "https://yts.mx/movies/star-wars-episode-v-the-empire-strikes-back-1980" },
  { title: "Star Wars", year: "1977", genre: "Sci-Fi", rating: "8.6", download: "https://yts.mx/movies/star-wars-episode-iv-a-new-hope-1977" },
  { title: "The Silence of the Lambs", year: "1991", genre: "Thriller", rating: "8.6", download: "https://yts.mx/movies/the-silence-of-the-lambs-1991" },
  { title: "Se7en", year: "1995", genre: "Thriller", rating: "8.6", download: "https://yts.mx/movies/se7en-1995" },
  { title: "The Departed", year: "2006", genre: "Thriller", rating: "8.5", download: "https://yts.mx/movies/the-departed-2006" },
  { title: "Gladiator", year: "2000", genre: "Action", rating: "8.5", download: "https://yts.mx/movies/gladiator-2000" },
  { title: "Titanic", year: "1997", genre: "Romance", rating: "7.9", download: "https://yts.mx/movies/titanic-1997" },
  { title: "The Notebook", year: "2004", genre: "Romance", rating: "7.8", download: "https://yts.mx/movies/the-notebook-2004" },
  { title: "Avengers Endgame", year: "2019", genre: "Action", rating: "8.4", download: "https://yts.mx/movies/avengers-endgame-2019" },
  { title: "Avengers Infinity War", year: "2018", genre: "Action", rating: "8.4", download: "https://yts.mx/movies/avengers-infinity-war-2018" },
  { title: "The Lion King", year: "1994", genre: "Animation", rating: "8.5", download: "https://yts.mx/movies/the-lion-king-1994" },
  { title: "Toy Story", year: "1995", genre: "Animation", rating: "8.3", download: "https://yts.mx/movies/toy-story-1995" },
  { title: "The Shining", year: "1980", genre: "Horror", rating: "8.4", download: "https://yts.mx/movies/the-shining-1980" },
  { title: "Get Out", year: "2017", genre: "Horror", rating: "7.8", download: "https://yts.mx/movies/get-out-2017" },
  { title: "The Hangover", year: "2009", genre: "Comedy", rating: "7.7", download: "https://yts.mx/movies/the-hangover-2009" },
  { title: "Superbad", year: "2007", genre: "Comedy", rating: "7.6", download: "https://yts.mx/movies/superbad-2007" },
  { title: "Deadpool", year: "2016", genre: "Comedy", rating: "8.0", download: "https://yts.mx/movies/deadpool-2016" },
  { title: "John Wick", year: "2014", genre: "Action", rating: "7.4", download: "https://yts.mx/movies/john-wick-2014" },
  { title: "The Equalizer", year: "2014", genre: "Action", rating: "7.2", download: "https://yts.mx/movies/the-equalizer-2014" },
  { title: "The Pursuit of Happyness", year: "2006", genre: "Drama", rating: "8.0", download: "https://yts.mx/movies/the-pursuit-of-happyness-2006" },
  { title: "The Social Network", year: "2010", genre: "Drama", rating: "7.7", download: "https://yts.mx/movies/the-social-network-2010" },
  { title: "The Wolf of Wall Street", year: "2013", genre: "Comedy", rating: "8.2", download: "https://yts.mx/movies/the-wolf-of-wall-street-2013" },
];

export const americanTV = [
  { title: "Game of Thrones", year: "2011", seasons: "8", rating: "9.2", download: "https://o2tvseries.com/game-of-thrones/" },
  { title: "Breaking Bad", year: "2008", seasons: "5", rating: "9.5", download: "https://o2tvseries.com/breaking-bad/" },
  { title: "The Office", year: "2005", seasons: "9", rating: "8.9", download: "https://o2tvseries.com/the-office-us/" },
  { title: "Stranger Things", year: "2016", seasons: "4", rating: "8.7", download: "https://o2tvseries.com/stranger-things/" },
  { title: "The Witcher", year: "2019", seasons: "3", rating: "8.2", download: "https://o2tvseries.com/the-witcher/" },
  { title: "Money Heist", year: "2017", seasons: "5", rating: "8.2", download: "https://o2tvseries.com/money-heist/" },
  { title: "Better Call Saul", year: "2015", seasons: "6", rating: "8.9", download: "https://o2tvseries.com/better-call-saul/" },
  { title: "The Walking Dead", year: "2010", seasons: "11", rating: "8.1", download: "https://o2tvseries.com/the-walking-dead/" },
  { title: "The Crown", year: "2016", seasons: "6", rating: "8.6", download: "https://o2tvseries.com/the-crown/" },
  { title: "The Mandalorian", year: "2019", seasons: "3", rating: "8.7", download: "https://o2tvseries.com/the-mandalorian/" },
  { title: "House of the Dragon", year: "2022", seasons: "2", rating: "8.5", download: "https://o2tvseries.com/house-of-the-dragon/" },
  { title: "The Last of Us", year: "2023", seasons: "1", rating: "8.8", download: "https://o2tvseries.com/the-last-of-us/" },
  { title: "Wednesday", year: "2022", seasons: "1", rating: "8.1", download: "https://o2tvseries.com/wednesday/" },
  { title: "The Boys", year: "2019", seasons: "4", rating: "8.7", download: "https://o2tvseries.com/the-boys/" },
  { title: "Succession", year: "2018", seasons: "4", rating: "8.8", download: "https://o2tvseries.com/succession/" },
  { title: "Yellowstone", year: "2018", seasons: "5", rating: "8.7", download: "https://o2tvseries.com/yellowstone/" },
  { title: "Peaky Blinders", year: "2013", seasons: "6", rating: "8.8", download: "https://o2tvseries.com/peaky-blinders/" },
  { title: "The Handmaid's Tale", year: "2017", seasons: "5", rating: "8.4", download: "https://o2tvseries.com/the-handmaids-tale/" },
  { title: "This Is Us", year: "2016", seasons: "6", rating: "8.7", download: "https://o2tvseries.com/this-is-us/" },
  { title: "Black Mirror", year: "2011", seasons: "6", rating: "8.7", download: "https://o2tvseries.com/black-mirror/" },
  { title: "The Bear", year: "2022", seasons: "3", rating: "8.6", download: "https://o2tvseries.com/the-bear/" },
  { title: "Fargo", year: "2014", seasons: "5", rating: "8.9", download: "https://o2tvseries.com/fargo/" },
  { title: "True Detective", year: "2014", seasons: "4", rating: "8.9", download: "https://o2tvseries.com/true-detective/" },
];
